openapi: 3.0.0
servers:
  - url: 'http://docr.kba.cloud:8765/'
info:
  version: 0.0.1
  title: OCR-D HTTP API
  description: This is a definition of the modules used for the OCR-D project.
  contact:
    email: volker.hartmann@kit.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Bildvorverarbeitung
    description: >
      Verfahren, die die Digitalisate für die Layout- und Texterkennung
      charakterisieren und optimieren.
  - name: Layouterkennung
    description: >
      Die Erfassung des korrekten, d.h. die Wiedergabe des logisch strukturell
      auf sich beziehenden Textflusses und hohe Textgenauigkeit.
  - name: Textoptimierung
    description: >
      Kombination mehrere OCR-Engines mit anschließender Nachkorrektur zur
      Verbesserung der Textergebnisse.
  - name: Modellbildung
    description: |
      Training der Modelle und Bereitstellung dieser.
  - name: Langzeitarchivierung
    description: >
      Sicherung der Langzeitverfügbarkeit und Referenzierbarkeit der gewonnenen
      Texte.
  - name: Qualitätssicherung
    description: |
      Bestimmung/Schätzung des Potenzials der einzelnen Komponenten.
paths:
  /layout/segmentation/tesserocr_segment_line:
    post:
      tags:
        - Layouterkennung
      summary: Segment page into regions with tesseract
      description: Segment page into regions with tesseract
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              type: object
              required:
                - mets
              properties:
                mets:
                  type: string
                  format: base64
                  description: METS file
                parameterJson:
                  type: object
                  description: Parameter definition provided by MP
                  schema:
                    type: object
                    properties: {}
      responses:
        '201':
          description: Successfully ran 'ocrd_tesserocr_segment_line'
          headers:
            Location:
              type: string
              format: uri
              description: URL of the resulting METS
  '/layout/segmentation/tesserocr_segment_line/{_id}':
    get:
      summary: Get Job result
      description: Get file thumbnail
      parameters:
        - name: id
          in: path
          description: Upload ID
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/vnd.ocrd.mets+zip:
              description: The workspace as a ZIP
            application/mets+xml:
              summary: The METS file
            text/status+plain:
              schema:
                type: string
                enum:
                  - RUNNING
                  - FAILED
                  - FINISHED
        '404':
          description: Job not found
        '410':
          description: Job deleted on server
      tags:
        - Layouterkennung
  /layout/segmentation/tesserocr_segment_region:
    post:
      tags:
        - Layouterkennung
      summary: Segment regions into lines with tesseract
      description: Segment regions into lines with tesseract
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              type: object
              required:
                - mets
              properties:
                mets:
                  type: string
                  format: base64
                  description: METS file
                parameterJson:
                  type: object
                  description: Parameter definition provided by MP
                  schema:
                    type: object
                    properties: {}
      responses:
        '201':
          description: Successfully ran 'ocrd_tesserocr_segment_region'
          headers:
            Location:
              type: string
              format: uri
              description: URL of the resulting METS
  '/layout/segmentation/tesserocr_segment_region/{_id}':
    get:
      summary: Get Job result
      description: Get file thumbnail
      parameters:
        - name: id
          in: path
          description: Upload ID
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/vnd.ocrd.mets+zip:
              description: The workspace as a ZIP
            application/mets+xml:
              summary: The METS file
            text/status+plain:
              schema:
                type: string
                enum:
                  - RUNNING
                  - FAILED
                  - FINISHED
        '404':
          description: Job not found
        '410':
          description: Job deleted on server
      tags:
        - Layouterkennung
  /recognition/tesserocr_recognize:
    post:
      tags:
        - Texterkennung
      summary: Recognize text in lines with tesseract
      description: Recognize text in lines with tesseract
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              type: object
              required:
                - mets
              properties:
                mets:
                  type: string
                  format: base64
                  description: METS file
                parameterJson:
                  type: object
                  description: Parameter definition provided by MP
                  schema:
                    type: object
                    properties: {}
      responses:
        '201':
          description: Successfully ran 'ocrd_tesserocr_recognize'
          headers:
            Location:
              type: string
              format: uri
              description: URL of the resulting METS
  '/recognition/tesserocr_recognize/{_id}':
    get:
      summary: Get Job result
      description: Get file thumbnail
      parameters:
        - name: id
          in: path
          description: Upload ID
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/vnd.ocrd.mets+zip:
              description: The workspace as a ZIP
            application/mets+xml:
              summary: The METS file
            text/status+plain:
              schema:
                type: string
                enum:
                  - RUNNING
                  - FAILED
                  - FINISHED
        '404':
          description: Job not found
        '410':
          description: Job deleted on server
      tags:
        - Texterkennung
components:
  headers: {}
  schemas: {}
